import type { Metadata } from "next";
import { Montserrat } from "next/font/google"; // Single font: Inter for all
import "./globals.css";
import AppToaster from "@/components/ui/AppToaster/AppToaster";

const montserrat = Montserrat({
  variable: "--font-sans", // Global var
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Regular, medium, semi-bold, bold
  display: "swap", // Quick fallback
});

export const metadata: Metadata = {
  title: "Yash Group",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        {children}
        <AppToaster />
      </body>
    </html>
  );
}